name: Prettier Format Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        working-directory: ./server
        run: npm ci

      - name: Run Prettier check
        working-directory: ./server
        run: npx prettier --check .
